# -*- coding: utf-8 -*-
"""Partial Matching.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-ohsdsm1olHM1wZqAfvqfLhBffWLFOAC
"""

pip install pandas sentence-transformers scikit-learn

import pandas as pd
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

# Load CSVs

# 📄 Example data for main_df
main_df = pd.DataFrame({
    "CleanAccountName": ["Acme Corp", "Beta Systems", "Zen Solutions","Bank Of America"],
    "CleanWebsite": ["acme.com", "betasys.de", "zensol.com","bofa.com"],
    "CleanCity": ["New York", "Berlin", "Austin","New York"],
    "CleanCountry": ["USA", "Germany", "USA","USA"]
})

# 📄 Example data for compare_df
compare_df = pd.DataFrame({
    "AccountName": ["Acme Ventures", "Systems GmbH", "Zen Sol","BOFA"],
    "Website": ["acmeinc.com", "beta-systems.de", "zen-solutions.com","bankofamerica.com"],
    "City": ["NYC", "Berlin", "Austin","New York"],
    "Country": ["United States", "Germany", "United States","USA"]})

# Combine fields into a single string for similarity matching
main_df["combined"] = main_df[['CleanAccountName', 'CleanWebsite', 'CleanCity', 'CleanCountry']].fillna('').agg(' '.join, axis=1)
compare_df["combined"] = compare_df[['AccountName', 'Website', 'City', 'Country']].fillna('').agg(' '.join, axis=1)

# Load LLM model for embeddings
model = SentenceTransformer('all-MiniLM-L6-v2')  # Fast and good

# Encode embeddings
main_embeddings = model.encode(main_df["combined"].tolist(), convert_to_tensor=True).cpu() # Move tensor to CPU
compare_embeddings = model.encode(compare_df["combined"].tolist(), convert_to_tensor=True).cpu() # Move tensor to CPU


# Compute cosine similarity
similarity_scores = cosine_similarity(main_embeddings, compare_embeddings)

# Get top matches
top_matches = []
for i, row in enumerate(similarity_scores):
    best_match_idx = row.argmax()
    score = row[best_match_idx]
    top_matches.append({
        "main_record": main_df.iloc[i]["combined"],
        "matched_with": compare_df.iloc[best_match_idx]["combined"],
        "similarity_score": score
    })

# Convert to DataFrame
matches_df = pd.DataFrame(top_matches)
matches_df = matches_df.sort_values(by="similarity_score", ascending=False)

# View results
print(matches_df.head(10))

import openai
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
import time

# 🔑 Set your OpenAI API key
openai.api_key = "--"   # Replace this with your actual API key

# Load CSVs
# 📄 Example data for main_df
main_df = pd.DataFrame({
    "CleanAccountName": ["Acme Corp", "Beta Systems", "Zen Solutions","Bank Of America"],
    "CleanWebsite": ["acme.com", "betasys.de", "zensol.com","bofa.com"],
    "CleanCity": ["New York", "Berlin", "Austin","New York"],
    "CleanCountry": ["USA", "Germany", "USA","USA"]
})

# 📄 Example data for compare_df
compare_df = pd.DataFrame({
    "AccountName": ["Acme Incorporated", "Beta Sys GmbH", "Zen Sol","BOFA"],
    "Website": ["acmeinc.com", "beta-systems.de", "zen-solutions.com","bankofmaerica.com"],
    "City": ["NYC", "Berlin", "Austin","New York"],
    "Country": ["United States", "Germany", "United States","USA"]})

# Combine fields into a single string for embedding
main_df["combined"] = main_df[["CleanAccountName", "CleanWebsite", "CleanCity", "CleanCountry"]].fillna("").agg(" ".join, axis=1)
compare_df["combined"] = compare_df[["AccountName", "Website", "City", "Country"]].fillna("").agg(" ".join, axis=1)

# Function to get embeddings from OpenAI
def get_embedding(text, model="text-embedding-3-small"):
    response = openai.embeddings.create(input=[text], model=model)
    return response.data[0].embedding

# Get embeddings with throttling
def get_all_embeddings(texts, delay=1):
    embeddings = []
    for text in texts:
        try:
            emb = get_embedding(text)
            embeddings.append(emb)
            time.sleep(delay)  # Be nice to the API
        except Exception as e:
            print(f"Error for text '{text}': {e}")
            embeddings.append([0]*1536)  # Fallback vector size
    return embeddings

# Get embeddings for both sets
main_embeddings = get_all_embeddings(main_df["combined"].tolist())
compare_embeddings = get_all_embeddings(compare_df["combined"].tolist())

# Convert to numpy arrays
main_embeddings = np.array(main_embeddings)
compare_embeddings = np.array(compare_embeddings)

# Calculate cosine similarity
similarity_matrix = cosine_similarity(main_embeddings, compare_embeddings)

# Find best match for each row in main_df
top_matches = []
for i, row_sim in enumerate(similarity_matrix):
    best_idx = np.argmax(row_sim)
    score = row_sim[best_idx]
    top_matches.append({
        "main_record": main_df.iloc[i]["combined"],
        "matched_with": compare_df.iloc[best_idx]["combined"],
        "similarity_score": round(score, 4)
    })

# Convert to DataFrame and display
match_df = pd.DataFrame(top_matches)
print(match_df.sort_values("similarity_score", ascending=False).head(10))

